### ISSUE TITLE
Error while running ./install.sh on local system and while deploying to heroku

### ISSUE THREAD

**Issue by architsingh15** [patriz/falcon-rest-api#7]
Due to package inconsistencies and deprecated functions in the previous versions, the build is failing during deployment on Heroku. This was replicated on the local system while running './install.sh'

Created a PR for the fix of that, please review and merge. Happy to explain why I did it, it is self-explanatory but still wouldn't mind. 
Thanks

**Comment by ziwon** [comment]
Please give it a try again since I've updated all the packages to the latest in `requirements/base.txt`
